### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by vasinov** [entangled-xyz/scotty#13]

**Comment by DieBauer** [comment]
Adding support for 2.13 is a great idea, as this project only depends on scalatest this might be unblocked fairly soon. 

And since scala 2.10-3 is supported by [scalatest](https://github.com/scalatest/scalatest/blob/3.1.x/project/scalatest.scala#L39) this can easily be added to the build file.

**Comment by vasinov** [comment]
@DieBauer, it seems like scalatest for Scala 2.13 [is still](https://search.maven.org/search?q=a:scalatest_2.13*) an RC but it's definitely okay for a test dependency. I'll try to resolve this sometime next week.
